repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
      - id: ruff-format
        args: [--check]

  - repo: local
    hooks:
      - id: pyright
        name: Run pyright
        entry: uv run pyright
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: pytest tests
        name: Run pytest tests
        entry: uv run pytest
        language: system
        types: [python]