name: Good quality
run-name: ${{ github.actor }} is checking good quality 🔎
on: [push, pull_request]

  #push:
    #branches:
      #- main
  #pull_request:
    #branches:
      #- main

jobs:

  check-linter:
    name: check-linter
    uses: ./.github/workflows/set-up.yaml

    steps:
      - name: check-linter
        run: uv run ruff check .
        shell: bash

  check-formatter:
    name: check-formatter
    uses: ./.github/workflows/set-up.yaml

    steps:
      - name: check-formatter
        run: uv run ruff format --check .
        shell: bash

  check-type-safety:
    name: check-formatter
    uses: ./.github/workflows/set-up.yaml

    steps:
      - name: check-type-safety
        run: uv run pyright
        shell: bash

  run-unit-test:
    name: run-unit-test
    uses: ./.github/workflows/set-up.yaml

    steps:
      - name: run-unit-test
        run: uv run pytest
        shell: bash