name: Good quality
run-name: ${{ github.actor }} is checking good quality 🔎
on: [push, pull_request]

  #push:
    #branches:
      #- main
  #pull_request:
    #branches:
      #- main

jobs:

  check-linter:
    name: check-linter
    runs-on: ubuntu-latest

    steps:
      - name: check-linter
      - uses: ./.github/actions
      - run: uv run ruff check .
        shell: bash

  check-formatter:
    name: check-formatter
    runs-on: ubuntu-latest

    steps:
      - name: check-formatter
      - uses: ./.github/actions
      - run: uv run ruff format --check .
        shell: bash

  check-type-safety:
    name: check-formatter
    runs-on: ubuntu-latest

    steps:
      - name: check-type-safety
      - uses: ./.github/actions
      - run: uv run pyright
        shell: bash

  run-unit-test:
    name: run-unit-test
    runs-on: ubuntu-latest

    steps:
      - name: run-unit-test
      - uses: ./.github/actions
      - run: uv run pytest
        shell: bash